name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Add target x86_64-unknown-linux-musl
      run: rustup add target x86_64-unknown-linux-musl
    - name: Add target x86_64-pc-windows-msvc
      run: rustup add target x86_64-pc-windows-msvc
    - name: Add target x86_64-apple-darwin
      run: rustup add target x86_64-apple-darwin
    - name: Add target aarch64-apple-darwin
      run: rustup add target aarch64-apple-darwin
    - name: Build
      run: cargo build --target x86_64-unknown-linux-musl --release --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Version
      run: ./target/x86_64-unknown-linux-musl/release/aemt --version
