name: Build

permissions:
  contents: write

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Add target x86_64-unknown-linux-musl
      run: rustup target add x86_64-unknown-linux-musl
    - name: Add target x86_64-pc-windows-msvc
      run: rustup target add x86_64-pc-windows-msvc
    - name: Add target x86_64-apple-darwin
      run: rustup target add x86_64-apple-darwin
    - name: Add target aarch64-apple-darwin
      run: rustup target add aarch64-apple-darwin
    - name: Run tests
      run: cargo test --verbose
    - name: Build
      run: cargo build --target x86_64-unknown-linux-musl --release --verbose
    - name: version
      run: echo "version=$(./target/x86_64-unknown-linux-musl/release/aemt --version | cut -d ' ' -f 2)" >> $GITHUB_OUTPUT
      id: version
    - name: release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: ${{ steps.version.outputs.version }}
        tag_name: v${{ steps.version.outputs.version }}-${{ substring(github.sha, 0, 7) }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
